USE [master]
GO

/****** Object:  Database [Scheduler]    Script Date: 15/06/2018 00:08:15 ******/
CREATE DATABASE [Scheduler]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Scheduler', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Scheduler.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Scheduler_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Scheduler_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Scheduler] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Scheduler].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Scheduler] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Scheduler] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Scheduler] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Scheduler] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Scheduler] SET ARITHABORT OFF 
GO

ALTER DATABASE [Scheduler] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Scheduler] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Scheduler] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Scheduler] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Scheduler] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Scheduler] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Scheduler] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Scheduler] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Scheduler] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Scheduler] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Scheduler] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Scheduler] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Scheduler] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Scheduler] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Scheduler] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Scheduler] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Scheduler] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Scheduler] SET RECOVERY FULL 
GO

ALTER DATABASE [Scheduler] SET  MULTI_USER 
GO

ALTER DATABASE [Scheduler] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Scheduler] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Scheduler] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Scheduler] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Scheduler] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Scheduler] SET QUERY_STORE = OFF
GO

USE [Scheduler]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Scheduler] SET  READ_WRITE 
GO


